import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image';
import pokemonWebsite from '../public/pokemon.png';
import selfPhoto from '../public/selfPhoto.jpg';
import tuitionSite from '../public/tuitionSite.png'


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-sm font-burtons'></h1>
            <ul className='flex items-center'>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Koh Chee Kiat</h2>
            <h3 className='text-2xl py-2'>Aspiring Full Stack Developer</h3>
          </div>
          <div className='relative bg-gradient-to-b from-teal-800 rounded-full w-80 h-80 mx-auto mt-3 overflow-hidden'>
            <Image src={selfPhoto}/>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-700'>
            <a className='flex items-center' href='https://www.linkedin.com/in/koh-chee-kiat-5bab8a255/'><AiFillLinkedin /></a>
            <a className='flex items-center' href='https://github.com/jaga991'><AiFillGithub /></a>
          </div>

        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1 text-center'>About Me</h3>
            <p className='text-md py-2 text-center px-20 leading-8 text-gray-800'>
              Hi there! I am currently a sophomore in Singapore University of technology and Design. I have a strong passion and desire to learn everything there is to know about software and web development, and I am working towards becoming a Full Stack Developer 
            </p>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className='mx-auto border' src={tuitionSite} width={400} height={400} />
              <h3 className="text-3xl font-medium pt-8 pb-2  ">
                Mockup tuition site
              </h3>
              <p className="py-2">
                Mockup site made using React and React Bootstrap framework
              </p>
              <div className='text-xl flex justify-center align-center gap-6 text-gray-700'>
                <a href='https://successnatfinal.vercel.app/'>Live Site</a>
                <a className='flex items-center' href='https://github.com/jaga991/successnatfinal'><AiFillGithub /></a>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className='mx-auto border' src={pokemonWebsite} width={400} height={400} />
              <h3 className="text-3xl font-medium pt-8 pb-2  ">
                Pokemon Card Memory Game
              </h3>
              <p className="py-2">
                Memory card game made using React and PokeAPI
              </p>
              <div className='text-xl flex justify-center align-center gap-6 text-gray-700'>
                <a href='https://pokemon-memory-gri2.vercel.app/'>Live Site</a>
                <a className='flex items-center' href='https://github.com/jaga991/Pokemon-Memory'><AiFillGithub /></a>
              </div>
            </div>
            
          </div>

        </section>
      </main>
    </>
  )
}
